# Generated by Django 5.0.3 on 2024-03-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phonenumber', models.CharField(max_length=15)),
                ('qualifications', models.CharField(choices=[('BSC', 'BSc'), ('MSC', 'MSc'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('BTECH', 'BTech'), ('MTECH', 'MTech')], max_length=10)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=10)),
                ('dateofbirth', models.DateField()),
                ('maritalstatus', models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=15)),
                ('interests', models.CharField(choices=[('INTERESTED', 'Interested'), ('NOTINTERESTED', 'Not Interested'), ('UNDECIDED', 'Undecided')], max_length=15)),
            ],
        ),
    ]
